import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { GlitchText } from "@/components/ui/glitch-text";

export default function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900/20 to-blue-900/20 p-4">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div className="text-center space-y-4">
          <GlitchText 
            className="text-6xl font-bold text-center bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent"
            dataText="ABOUT SEPHYX"
          >
            ABOUT SEPHYX
          </GlitchText>
          <p className="text-lg text-gray-300 max-w-2xl mx-auto">
            The underground streetwear collective born from the digital rebellion
          </p>
        </div>

        {/* Brand Story */}
        <Card className="bg-black/20 backdrop-blur-sm border-purple-500/20">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-purple-400">
              Our Story
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-gray-300 leading-relaxed">
              SEPHYX emerged from the digital underground in 2025, born from a collective 
              of rogue designers, hackers, and street artists who refused to conform to 
              the mainstream fashion industry's corporate algorithms.
            </p>
            <p className="text-gray-300 leading-relaxed">
              We believe that true style cannot be manufactured by AI or mass-produced 
              by machines. It must be crafted by human hands, worn by rebels, and 
              earned through the streets.
            </p>
          </CardContent>
        </Card>

        {/* Mission */}
        <Card className="bg-black/20 backdrop-blur-sm border-blue-500/20">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-blue-400">
              The Mission
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-gray-300 leading-relaxed">
              To create authentic streetwear that tells the story of the digital 
              resistance. Every piece is designed to be a statement against 
              conformity and a badge of honor for those who dare to be different.
            </p>
            <div className="flex flex-wrap gap-2">
              <Badge variant="outline" className="border-purple-500/50 text-purple-400">
                Authentic Design
              </Badge>
              <Badge variant="outline" className="border-blue-500/50 text-blue-400">
                Limited Edition
              </Badge>
              <Badge variant="outline" className="border-green-500/50 text-green-400">
                Street Tested
              </Badge>
              <Badge variant="outline" className="border-red-500/50 text-red-400">
                Rebel Approved
              </Badge>
            </div>
          </CardContent>
        </Card>

        {/* Values */}
        <div className="grid md:grid-cols-3 gap-4">
          <Card className="bg-black/20 backdrop-blur-sm border-purple-500/20">
            <CardHeader>
              <CardTitle className="text-lg font-bold text-purple-400">
                Authenticity
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-300 text-sm">
                Every design is hand-crafted by real artists, not generated by algorithms.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-black/20 backdrop-blur-sm border-blue-500/20">
            <CardHeader>
              <CardTitle className="text-lg font-bold text-blue-400">
                Quality
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-300 text-sm">
                Premium materials and construction built to survive the streets.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-black/20 backdrop-blur-sm border-green-500/20">
            <CardHeader>
              <CardTitle className="text-lg font-bold text-green-400">
                Community
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-300 text-sm">
                Built by and for the underground culture that refuses to be silenced.
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Contact */}
        <Card className="bg-black/20 backdrop-blur-sm border-red-500/20">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-red-400">
              Join the Resistance
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-gray-300 leading-relaxed">
              Ready to break free from the corporate fashion machine? Join our 
              underground network and be part of something bigger than yourself.
            </p>
            <div className="flex flex-wrap gap-4 text-sm">
              <div className="text-purple-400">
                <strong>Discord:</strong> sephyx.underground
              </div>
              <div className="text-blue-400">
                <strong>Instagram:</strong> @sephyx_official
              </div>
              <div className="text-green-400">
                <strong>Email:</strong> resistance@sephyx.co
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}